version: '3'

services:
  api:
    build: .
    container_name: flask-docker.api
    ports:
      - "5000:5000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
#    command: flask run --host 0.0.0.0 --port 5000
